### ISSUE TITLE
European Time format shutdown.xml

### ISSUE THREAD

**Issue by marcok-cm** [teknowledgist/TeknowTools#1]
Hi,

How can i change CheckAutoReboot.vbs to use it with the European Time Format?

<RebootPoint>01/19/2019 18:00:00</RebootPoint>

But is has to be:

<RebootPoint>19/01/2019 18:00:00</RebootPoint>

**Comment by teknowledgist** [comment]
Hi,

I should have noticed that "Ameri-centric" issue earlier, though maybe I can blame MS for making the default that way.  :smile: 

I have updated the code, but if you want to modify it yourself, go to line 1879 and change `get-date -Date $RebootPoint -Format d` to `get-date -Date $RebootPoint -UFormat %x`

Hope you are finding it useful.

**Comment by marcok-cm** [comment]
Hi,

Thanks for the quick answer.

We are currently using the VBS version. On which line can i change it there?

**Comment by teknowledgist** [comment]
Hi,

Oh!  Line 729.  Change the `-format f` to `-uformat %x`.  I've pushed that change up too.

You should consider the newer, PoSh version.  It is easier to read and modify than that VBS monstrosity.  :smile:

**Comment by marcok-cm** [comment]
Hi,

That didn't work, it's still: <RebootPoint>01/18/2019 17:00:00</RebootPoint>

**Comment by teknowledgist** [comment]
Hi,

Just to be clear, where are you seeing this?

Thanks.

**Comment by marcok-cm** [comment]
Hi,

In the shutdown.xml

**Comment by teknowledgist** [comment]
Hrmm... That is in the VBS code (in which I am not very good).

If you look at lines 629 and 659, there is a `Now` function.  I thought that was supposed to use the local time format as set in the control panel.  You could try change those lines to enclose the `Now` like this:

    FormatDateTime(Now(),0)

That may more explicitly use the locale of the computer.

Let me know if that works.  (I can't test it right now.)  If it doesn't, then I will probably just use a universal `yyyy.MM.dd-HH.mm.ss` format.

Thanks and sorry for the hassle.

**Comment by marcok-cm** [comment]
Hi,

Unfortunately, that did nothing. Changing the universal format also did nothing. It seems like the RebootPoint rule has not changed.

When i use the PS version i get the following error:

Exception calling "SetAccessRule" with "1" argument(s): "Kan een aantal of alle id-verwijzingen niet omzetten."
At C:\ProgramData\ITServices\Reboot\Check-AutoReboot.ps1:1375 char:10
+          $Acl.setaccessrule($rule)
+          ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException

**Comment by teknowledgist** [comment]
Unfortunately, the PowerShell version of this script will suffer the same VBS date issue you are seeing because that portion of the process is buried in the HTA (with embedded VBS).  I will see if I can wrestle the VBS-created xml log entries into a more universal format.

Note that the xml log is mostly depreciated in the PoSh version as (more complete) logging is in the system application log.  The PowerShell script *should* create the shutdown.xml file, but it doesn't rely on in any longer.  

I am looking into the error you submitted.  I suspect it is another language issue, but I'm confident there is a solution to this one.

**Comment by teknowledgist** [comment]
I just pushed a couple changes.

1. I pretty confident the error is resolved.  Granting rights to "Authenticated Users" is now done by SID.
2. If I did it right, the date in the XML log should now be in the form `yyyy-MM-ddThh:mm:ss` which is locale-independent and a recognized datestring in PowerShell.  I can't test that right now, unfortunately.

I made these changes in both the .ps1 and .vbs versions.

**Comment by marcok-cm** [comment]
The output of your default VBS is now:

<?xml version="1.0"?>
<Root>
  <RebootReason>
  </RebootReason>
  <TriggerPoint>16-1-2019 22:05:40</TriggerPoint>
  <Acknowledgements>
    <Stamp Mark="0">1899-12-30T0:0:0</Stamp>
  </Acknowledgements>
  <Shutdown>
  </Shutdown>
  <Quiet>False</Quiet>
  <RebootPoint>01/25/2019 17:00:00</RebootPoint>
</Root>

The first (Triggerpoint) is good, but this has always been. The 2nd is not good anymore.

Do I have to adjust something?

**Comment by marcok-cm** [comment]
XML didn't work here.

 TriggerPoint 16-1-2019 22:12:59
 Stamp Mark "0" 1899-12-30T0:0:0
  RebootPoint 01/25/2019 17:00:00

**Comment by teknowledgist** [comment]
Doh!  I had a really stupid coding error.  I've pushed up the changes again.  Hopefully they work.  Sorry for all the hassle.

**Comment by marcok-cm** [comment]
Still the same problem... Can i send my full configuration to you? Maybe you can see where the fault is.

**Comment by teknowledgist** [comment]
Sure.  I'd like to figure out how to get this working properly.

**Comment by teknowledgist** [comment]
My direct email is my username at gmail.

**Comment by teknowledgist** [comment]
The most recent PR has been tested and stores all the DateTimes in the xml/log in a universal format `yyyy-MM-dd hh:mm:ss`.  The date appended to the file name when the `.xml` is converted to a `.log` cannot have ":" and I didn't want spaces, so it has not changed from `yyyy.MM.dd-hh.mm`.

Both the PowerShell and VBS versions are fixed.
